version: "3"

services:
  backend:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - db
    env_file:
      local.env
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      local.env

volumes:
  postgres_data: