version: "3.5"
services:
  python-code-test:
    build: ./app
    command: sh -c "sleep 5 ; python manage.py migrate -v 0 ; python manage.py init_users && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

volumes:
  postgres_data:
