# Generated by Django 3.1.4 on 2020-12-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('season', models.PositiveIntegerField()),
                ('release_date', models.DateField()),
                ('imdb_rating', models.FloatField()),
            ],
        ),
    ]
