# Generated by Django 3.1 on 2020-12-17 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('total_seasons', models.PositiveIntegerField()),
                ('rating', models.FloatField()),
                ('imdbId', models.CharField(max_length=256)),
                ('released', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('released', models.DateTimeField()),
                ('rating', models.FloatField()),
                ('imdbId', models.CharField(max_length=256)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.movie')),
                ('season', models.PositiveIntegerField()),
                ('episode', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('episode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviedata.episode')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
